language: ruby
rvm:
  - rvm 2.1.1
  - rvm 2.1.5
  - rvm 2.2.0
  - rvm 2.2.1
  - rvm 2.2.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql
  - sudo apt-get install -qq postgresql-server-dev-9.3
  - sudo apt-get install -qq libpq-dev
